language: ruby
rbenv:
  - 2.4.3
env:
  - DB=pgsql

services:
  - postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database crdcprojectmanagement_test;' -U postgres

