# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1aeba82838680da02069c4a6ec7ec353a4dab29701b55fdd18aa3db0aacd1e22f9a3ff2fd28c0140567fda779dc92aa989461faae5a6164cfb76ee8cb9390913

test:
  secret_key_base: 5f6671b517e781741496331d67ffcd080187f2c8ed94a7d5833f3375c2e7480377e04fb8185af2f098f39ae4ca749d73788a85133ce090c82d58803765cda203

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
